### ISSUE TITLE
should factor_in_order be exported?

### ISSUE THREAD

**Issue by sebkopf** [isoverse/isoorbi#15]
should this function be exported by isoorbi or should `forcats` instead be a suggested package in the DESCRIPTION (so we can use `forcats::in_order()` in vignettes? I'm leaning towards the latter but implemented the prior for now. What do you all think?

**Comment by 123caj** [comment]
In the core `isoorbi` package we want to minimize dependencies on other packages. If the factor_in_order() helper function works well that's looking fine to me as is, without importing `forcats` for the time being

**Comment by 123caj** [comment]
I now see, the function is exported... This gets a bit confusing in the help pages. 

Is there a way to use it as an internal function only? As far as I can see `factor_in_order` is only used in an internal function atm, no?

```
# internal function to determine data groups
# @param dataset assumes is in the correct order
determine_data_groups <- function(dataset) {...
```

**Comment by sebkopf** [comment]
yes, not a problem as internal but then in the vignette we need to `library(forcats)` as we can't use internal functions in the vignette - that okay? that doesn't mean `forcats` has to be in depends, just in suggested
