### ISSUE TITLE
Flow chart in README is not showing on website (for me)

### ISSUE THREAD

**Issue by 123caj** [isoverse/isoorbi#43]
```
## Package layout

![](figure_flowchart.png)
```

using pkgdown::build_site()

<img width="1393" alt="image" src="https://github.com/isoverse/isoorbi/assets/5480056/d4f94f28-6a60-4de5-8135-b471ed499f93">

**Comment by SabrielxD** [comment]
yes, because it has to be in a different folder. it is fixed on my computer already but I am still working on errors in the package during R CMD check so not pushed to GitHub yet
