### ISSUE TITLE
Need smaller test file for dual inlet

### ISSUE THREAD

**Issue by 123caj** [isoverse/isoorbi#7]
Replace `extdata/testfile_DualInlet.isox` with a smaller version (e.g. 10 microscans) to meet CRAN file size limits (package total max 5MB)

**Comment by sebkopf** [comment]
@123caj do you think it'd be good to also switch to a file that has the whole start-up section in it to demonstrate that?

**Comment by sebkopf** [comment]
we still need the smaller file to resolve the remaining NOTE for cran check

**Comment by 123caj** [comment]
Added a smaller test file called testfile_dual_inlet_new.isox. Is this ok? 

Kristyna and I collected the data on 18-May-2023 (Nitrate, 5min startup time, 7 blocks a 10 min; 10 microscans). I removed 4/5 scans to keep the file size <2MB...

**Comment by sebkopf** [comment]
yes, thank you, i will test with this later, gotta take a few days break from programming to focus on tenure stuff

**Comment by 123caj** [comment]
More or less done
